<?php

echo "<h1>Movie Listing</h1>";

echo PHP_EOL;

echo PHP_EOL;

	echo $this->tag->linkTo(
	"?sort=rating",
    "rating "
    );

    echo $this->tag->linkTo(
	"?sort=alphabetical",
    "alphabetical "
    );

    echo $this->tag->linkTo(
	"?sort=release_data",
    "release_date "
    );

	echo "<br/>";

for($i=0; $i<count($movies); $i++){

	echo $this->tag->linkTo(
	"info/{$movies[$i]->title}",
    $movies[$i]->title
);

	echo "<br/>";

}